### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [mafer09/craving-meter#1]
👋 Hi @mafer09 ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Learn` repo. This means that you would like to teach students, step by step, how to build this project. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/mafer09/craving-meter/issues/2
- [ ] https://github.com/mafer09/craving-meter/issues/3
- [x] https://github.com/mafer09/craving-meter/issues/4
- [ ] https://github.com/mafer09/craving-meter/issues/5
- [x] https://github.com/mafer09/craving-meter/issues/6

**Comment by mafer09** [comment]
Hi @ericdrosado,

A bit of background: This project was based on a class project that I submitted with a partner (hence the other contributor). I wanted specifically showcase Selenium webserver for web scraping which is only phase 1 (out of 3) of the overall project repo. The reason why I choose to submit/showcase phase 1 is due to the little step by step documentation available online to set up and use selenium. 

My questions for you are:
1. Should I be creating a new repo which only focuses on phase 1 and removes all the extra irrelevant things? (like solver configuration and .py executable of craving meter? For reference here is an architecture diagram in which I have box highlighted "phase 1" 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/9340526/168890141-08826703-80b0-48ed-bf25-ac3c5763c7c9.png">

2. Will the other contributor be notified of all the changes? I choose to do this on my own and I dont want her github/mailbox to be flooded with this work

Looking forward to your response

**Comment by ericdrosado** [comment]
I am very happy to hear that you want to teach others about Selenium ❤️  

> Should I be creating a new repo which only focuses on phase 1

If you are interested in only showcasing phase 1, then I would recommend creating a new repo with the code for phase 1. However, you should notify your former partner that you are interested in doing this since you worked on this project together. 

> Will the other contributor be notified of all the changes? 

This is another reason to create a new repo, so your partner does not receive messages. Again, I highly recommend that you confirm with your partner if they are OK with you moving forward with this project. 😄

**Comment by mafer09** [comment]
Yeah, Selenium webdriver is a fun tool to use but its not the easiest to get started with. 

> If you are interested in only showcasing phase 1, then I would recommend creating a new repo with the code for phase 1.   

ok I have created [web-consumer](https://github.com/mafer09/web-consumer) repo in which I included my  some of my original notes/code when I got started on setting it up as well as the phase 1 code referenced in the craving-meter repo. 

- [ ] Could you go ahead and transfer over the issues and tasks to that repo?

> However, you should notify your former partner that you are interested in doing this since you worked on this project together.   

I have already notified her about it. Phase 1 is the code that I wrote on my own so there are no issues there in regards to authorship. I just wanted to make sure that she didnt get bothered by something that I decided to do on my free time. 

Which reminds me.... as selfish as it sounds I did sign up for doing this work because of the promise of GitHub swag that was mentioned in the GitHub Education email. Now there is a part of me that it is also doing it to help others but my top reason is my obsession with octocat.... So when does that come in play?  😃

**Comment by ericdrosado** [comment]
> Could you go ahead and transfer over the issues and tasks to that repo?

I'll begin the transfer.

> but my top reason is my obsession with octocat.... So when does that come in play?

😅 @mafer09 we are also big fans of :octocat:, so we understand. Swag will be sent to students who were selected and completed the issues generated by the GitHub mentor. "Completed" means that a mentor has approved all the changes. Also, all the issues must be completed before June 1st.
